/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cli_libVNFFrontend_Interface */

#ifndef _Included_cli_libVNFFrontend_Interface
#define _Included_cli_libVNFFrontend_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cli_libVNFFrontend_Interface
 * Method:    __init_SFC
 * Signature: (I[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cli_libVNFFrontend_Interface__1_1init_1SFC
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     cli_libVNFFrontend_Interface
 * Method:    __VNFThread
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cli_libVNFFrontend_Interface__1_1VNFThread
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     cli_libVNFFrontend_Interface
 * Method:    _callBack
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_cli_libVNFFrontend_Interface__1callBack
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     cli_libVNFFrontend_Interface
 * Method:    __handle_done
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cli_libVNFFrontend_Interface__1_1handle_1done
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
