/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libVNFFrontend_NativeInterface */

#ifndef _Included_libVNFFrontend_NativeInterface
#define _Included_libVNFFrontend_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libVNFFrontend_NativeInterface
 * Method:    __init_SFC
 * Signature: (I[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libVNFFrontend_NativeInterface__1_1init_1SFC
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     libVNFFrontend_NativeInterface
 * Method:    __VNFThread
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_libVNFFrontend_NativeInterface__1_1VNFThread
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     libVNFFrontend_NativeInterface
 * Method:    _execute_sa_udf
 * Signature: (JI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_libVNFFrontend_NativeInterface__1execute_1sa_1udf
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint);

/*
 * Class:     libVNFFrontend_NativeInterface
 * Method:    __txn_finished
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_libVNFFrontend_NativeInterface__1_1txn_1finished
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
