/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_java_Loader_Loader */

#ifndef _Included_utils_java_Loader_Loader
#define _Included_utils_java_Loader_Loader
#ifdef __cplusplus
extern "C" {
#endif
#undef utils_java_Loader_Loader_MIN_PRIORITY
#define utils_java_Loader_Loader_MIN_PRIORITY 1L
#undef utils_java_Loader_Loader_NORM_PRIORITY
#define utils_java_Loader_Loader_NORM_PRIORITY 5L
#undef utils_java_Loader_Loader_MAX_PRIORITY
#define utils_java_Loader_Loader_MAX_PRIORITY 10L
/*
 * Class:     utils_java_Loader_Loader
 * Method:    WorkingThread
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_utils_java_Loader_Loader_WorkingThread
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     utils_java_Loader_Loader
 * Method:    TxnUDF
 * Signature: (Lutils/java/StateAccess/StateAccess;)I
 */
JNIEXPORT jint JNICALL Java_utils_java_Loader_Loader_TxnUDF
  (JNIEnv *, jobject, jobject);

/*
 * Class:     utils_java_Loader_Loader
 * Method:    PostTxnUDF
 * Signature: (Lutils/java/StateAccess/StateAccess;)I
 */
JNIEXPORT jint JNICALL Java_utils_java_Loader_Loader_PostTxnUDF
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
