/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary */

#ifndef _Included_intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary
#define _Included_intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary_init
  (JNIEnv *, jobject);

/*
 * Class:     intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary
 * Method:    connect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary_connect
  (JNIEnv *, jobject);

/*
 * Class:     intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary
 * Method:    write
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary_write
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary
 * Method:    read
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_intellistream_morphstream_engine_db_impl_remote_RemoteCallLibrary_read
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
