apiVersion: v1
kind: Pod
metadata:
  name: rdma-driver-pod
  labels:
    app: rdma-driver
spec:
  containers:
    - name: driver-container
      image: curryzhao/rtfaas
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
      resources:
        requests:
          cpu: "4"
          memory: "16Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
      securityContext:
        capabilities:
          add: ["IPC_LOCK"]
      volumeMounts:
        - name: rdma-devices
          mountPath: /dev/infiniband
  volumes:
    - name: rdma-devices
      hostPath:
        path: /dev/infiniband
